=== Alejandro27ML/Lenguaje-de-Marcas/Clase14/ejercicio1.dtd
<!ELEMENT biblioteca (libro+)>
    <!ELEMENT libro (titulo, autor+, año?, genero)>
    <!-- Para los atriburos (como ids)
    Primero ponemos donde está (libro)
    identificador 
    Cadena alfanumericas (CDATA)
    único (id) <-
    puede uno de estre 2 valores(valor1|valor2) -->
    <!ATTLIST libro id ID #REQUIRED>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT año (#PCDATA)>
    <!ELEMENT genero (#PCDATA)>

=== Alejandro27ML/Lenguaje-de-Marcas/Clase14-dtd/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE biblioteca SYSTEM "ejercicio1.dtd">

<biblioteca>
    <libro id="e1">
        <titulo></titulo>
        <autor></autor>
        <a単o></a単o>
        <genero></genero>
    </libro>

    <libro id="e2">
        <titulo></titulo>
        <autor></autor>
        <a単o></a単o>
        <genero></genero>
    </libro>

</biblioteca>
